using NoraBar.Models;

namespace NoraBar.Services;

internal sealed class LauncherLocalization
{
    private readonly AppLanguage _language;
    internal LauncherLocalization(AppLanguage language) => _language = language;
    private string Pick(string japanese, string english) => _language == AppLanguage.Japanese ? japanese : english;

    public string Launcher => Pick("ランチャー", "Launcher");
    public string SearchTooltip => Pick("登録アイテムとインストール済みアプリを検索", "Search launcher items and installed applications");
    public string PagesItems => Pick("ページとアイテム", "Pages & Items");
    public string Pages => Pick("ページ", "Pages");
    public string AddPage => Pick("ページを追加", "Add page");
    public string RemovePage => Pick("ページを削除", "Remove page");
    public string MovePageUp => Pick("ページを上へ", "Move page up");
    public string MovePageDown => Pick("ページを下へ", "Move page down");
    public string PageName => Pick("ページ名", "Page name");
    public string Groups => Pick("グループ", "Groups");
    public string AddGroup => Pick("グループを追加", "Add group");
    public string RemoveGroup => Pick("グループを削除", "Remove group");
    public string MoveGroupUp => Pick("グループを上へ", "Move group up");
    public string MoveGroupDown => Pick("グループを下へ", "Move group down");
    public string GroupName => Pick("グループ名", "Group name");
    public string ItemsDropHint => Pick("アイテム — ファイルまたはフォルダーをここへドロップして追加", "Items — drop files or folders here to add");
    public string InstalledApps => Pick("インストール済みアプリ", "Installed Apps");
    public string RunningApps => Pick("実行中のアプリ", "Running Apps");
    public string File => Pick("ファイル", "File");
    public string Folder => Pick("フォルダー", "Folder");
    public string Url => Pick("URL", "URL");
    public string Remove => Pick("削除", "Remove");
    public string Locate => Pick("場所を指定…", "Locate…");
    public string MoveItemUp => Pick("アイテムを上へ", "Move item up");
    public string MoveItemDown => Pick("アイテムを下へ", "Move item down");
    public string ItemEditor => Pick("アイテム編集 / 詳細オプション", "Item editor / Advanced options");
    public string Name => Pick("名前", "Name");
    public string Target => Pick("ターゲット", "Target");
    public string TargetNotFound => Pick("ターゲットが見つかりません", "Target not found");
    public string ItemType => Pick("種類", "Type");
    public string ExistingInstanceBehavior => Pick("起動中の動作", "When already running");
    public string Arguments => Pick("引数", "Arguments");
    public string WorkingDirectory => Pick("作業フォルダー", "Working directory");
    public string CustomIcon => Pick("カスタムアイコン", "Custom icon");
    public string Browse => Pick("参照…", "Browse…");
    public string SpecificBrowser => Pick("指定ブラウザー", "Specific browser");
    public string RunAsAdministrator => Pick("管理者として実行", "Run as administrator");
    public string VisualLauncherEditorTitle => Pick("NoraBar — ビジュアル ランチャー エディター", "NoraBar — Visual Launcher Editor");
    public string VisualEditorDescription => Pick("専用のビジュアルエディターを開いて、ページ・グループ・アイテムをドラッグ＆ドロップで見たまま編集します。", "Open a dedicated visual editor to view and edit pages, groups, and items via drag-and-drop.");
    public string OpenVisualEditor => Pick("🚀 ビジュアルエディターを開く", "🚀 Open Visual Editor");
    public string SmartLauncher => Pick("Smart ランチャー", "Smart Launcher");
    public string InspectorNoSelectionHint => Pick("アイテムを選択すると、ここでプロパティを詳細編集できます。", "Select an item to edit its detailed properties here.");
    public string AddPageAction => Pick("＋ ページ追加", "＋ Add Page");
    public string DefaultItemIcon => "📦";
    public string Smart => "Smart";
    public string EnableSmart => Pick("ローカル Smart 候補を有効化", "Enable local Smart suggestions");
    public string SmartPrivacy => Pick("候補は端末内の使用時刻、頻度、前面表示時間、時間帯、アプリの文脈だけを使用します。データは送信されません。", "Suggestions use only local recency, frequency, foreground duration, time-of-day and application context. No data is transmitted.");
    public string ClearUsage => Pick("ランチャーの使用履歴を消去", "Clear Launcher usage history");
    public string Rules => Pick("ルール", "Rules");
    public string RulesDescription => Pick("曜日、時間帯、前面アプリの条件でページを有効化します。設定したすべての条件が一致する必要があります。", "Rules activate a page using weekday, time range and foreground application conditions. All configured conditions must match.");
    public string Priority => Pick("優先度", "Priority");
    public string MoveRuleUp => Pick("ルールを上へ", "Move rule up");
    public string MoveRuleDown => Pick("ルールを下へ", "Move rule down");
    public string Add => Pick("追加…", "Add…");
    public string Edit => Pick("編集…", "Edit…");
    public string Delete => Pick("削除", "Delete");
    public string Shortcuts => Pick("ショートカット", "Shortcuts");
    public string OpenLauncher => Pick("ランチャーを開く", "Open Launcher");
    public string OpenSearch => Pick("ランチャー検索を開く", "Open Launcher Search");
    public string ShortcutHint => Pick("例: Ctrl+Alt+L。空欄で無効。", "Example: Ctrl+Alt+L. Leave blank to disable.");
    public string SearchShortcutHint => Pick("例: Ctrl+Alt+Space。空欄で無効。", "Example: Ctrl+Alt+Space. Leave blank to disable.");
    public string ApplyShortcuts => Pick("ショートカットを適用", "Apply shortcuts");
    public string ShortcutNeedsModifier => Pick("Ctrl+Alt+L のように修飾キーとキーを指定してください。", "Use at least one modifier and a key, for example Ctrl+Alt+L.");
    public string ShortcutModifierInvalid => Pick("ショートカットの修飾キーが正しくありません。", "The shortcut modifier is invalid.");
    public string GlobalShortcutNeedsModifier => Pick("グローバルショートカットには修飾キーが必要です。", "Global shortcuts require at least one modifier.");
    public string GlobalShortcutKeyInvalid => Pick("ショートカットのキーが正しくありません。", "The shortcut key is invalid.");
    public string GlobalShortcutConflict => Pick("このショートカットは別のアプリケーションで使用されています。", "The shortcut is already registered by another application.");
    public string Open => Pick("開く", "Open");
    public string OpenNew => Pick("新しいインスタンスを開く", "Open new instance");
    public string SwitchWindow => Pick("ウィンドウを切り替え", "Switch window");
    public string Close => Pick("閉じる", "Close");
    public string ForceQuit => Pick("強制終了…", "Force quit…");
    public string EditInSettings => Pick("設定で編集", "Edit in Settings");
    public string Loading => Pick("読み込み中…", "Loading…");
    public string NoOpenWindows => Pick("開いているウィンドウはありません", "No open windows");
    public string ChooseFile => Pick("ファイルまたはアプリを選択", "Choose a file or application");
    public string ChooseFolder => Pick("フォルダーを選択", "Choose a folder");
    public string Enabled => Pick("有効", "Enabled");
    public string Weekdays => Pick("曜日", "Weekdays");
    public string WeekdayHint => Pick("カンマ区切り（例: Monday,Tuesday）", "Comma-separated, for example Monday,Tuesday");
    public string TimeRange => Pick("時間帯", "Time range");
    public string TimeRangeHint => Pick("HH:mm-HH:mm。空欄は常時", "HH:mm-HH:mm; blank means any time");
    public string ForegroundIdentity => Pick("前面アプリの識別子", "Foreground application identity");
    public string TargetPage => Pick("対象ページ", "Target page");
    public string AddPageTitle => Pick("ページを追加", "Add page");
    public string DefaultPageName => Pick("ページ", "Page");
    public string AddGroupTitle => Pick("グループを追加", "Add group");
    public string DefaultGroupName => Pick("アプリケーション", "Applications");
    public string AddUrlTitle => Pick("URL を追加", "Add URL");
    public string UrlPrompt => Pick("HTTP または HTTPS の URL", "HTTP or HTTPS URL");
    public string InvalidUrl => Pick("HTTP または HTTPS の URL のみ使用できます。", "Only HTTP and HTTPS URLs are supported.");
    public string RunningApplicationsTitle => Pick("実行中のアプリ", "Running applications");
    public string InstalledApplicationsTitle => Pick("インストール済みアプリ", "Installed applications");
    public string ImageFilter => Pick("画像とアイコン|*.png;*.jpg;*.jpeg;*.bmp;*.ico|すべてのファイル|*.*", "Images and icons|*.png;*.jpg;*.jpeg;*.bmp;*.ico|All files|*.*");
    public string ClearUsageConfirmation => Pick("ランチャーのローカル使用履歴をすべて消去しますか？", "Clear all local Launcher usage history?");
    public string ShortcutsSaved => Pick("ショートカットを保存しました。", "Shortcuts saved.");
    public string LauncherItemTitle => Pick("ランチャーアイテム", "Launcher item");
    public string LauncherRuleTitle => Pick("ランチャールール", "Launcher rule");
    public string InvalidRuleCondition => Pick("曜日または時間帯が正しくありません。", "The weekday or time range is invalid.");
    public string RunAsAdministratorMenu => Pick("管理者として実行", "Run as administrator");
    public string OpenFileLocation => Pick("ファイルの場所を開く", "Open file location");
    public string UntitledWindow => Pick("タイトルなしのウィンドウ", "Untitled window");
    public string Switch => Pick("切り替え", "Switch");
    public string ForceQuitConfirmation => Pick("このアプリケーションを強制終了しますか？保存していない作業は失われる可能性があります。", "Force quit this application? Unsaved work may be lost.");
    public string Ok => "OK";
    public string Cancel => Pick("キャンセル", "Cancel");
}
