using System.Collections.Generic;
using NoraBar.Models;

namespace NoraBar.Services
{
    public enum LocalizationKey
    {
        WindowTitle,
        AppSubtitle,
        HudSettings,
        About,
        DesignStyle,
        DesignStyleDescription,
        ProgressBar,
        ProgressBarDescription,
        ShowLyrics,
        ShowLyricsDescription,
        Startup,
        StartupDescription,
        Language,
        LanguageDescription,
        Japanese,
        English,
        Version,
        CheckUpdates,
        CheckUpdatesDescription,
        CheckUpdatesButton,
        GitHubRepository,
        GitHubRepositoryDescription,
        OpenRepository,
        OpenSourceLicenses,
        OpenSourceLicensesDescription,
        ShowLicenses,
        LivePreview,
        Close,
        ThirdPartyLicenses,
        Update,
        Download,
        SettingsMenu,
        Exit,
        CheckingUpdates,
        UpdateAvailable,
        UpToDate,
        UpdateFailed,
        LicenseIntroTitle,
        LicensePackageVersion,
        LicenseLabel,
        LicenseDetails,
        ThirdPartyTab,
        LoadingLyrics,
        LyricsNotFound,
        LyricsNetworkError,
        WindowPosition,
        WindowPositionDescription,
        ChangePosition,
        ResetPosition,
        FinishPositionEdit,
        ResetSettings,
        ResetSettingsDescription,
        ResetAllSettings,
        ResetConfirmTitle,
        ResetConfirmMessage,
        ResetConfirmYes,
        ResetConfirmNo,
        TextScrollMode,
        TextScrollModeDescription,
        TextScrollDisabled,
        TextScrollAlways,
        TextScrollHoverOnly,
        CheckUpdateOnStartup,
        CheckUpdateOnStartupDescription,
        UpdateAvailableButton,
        RestartVisualizer,
        RestartVisualizerDescription,
        RestartVisualizerButton,
        DisableExpandOnFullscreen,
        DisableExpandOnFullscreenDescription,
        GeneralSettings,
        HudSelection,
        HudSelectionDescription,
        SharedDisplaySettings,
        SelectedHudSettings,
        MusicHudName,
        HomeHudName,
        NavigationStyle,
        NavigationStyleDescription,
        NavigationRightRail,
        NavigationTopTabs,
        StartupHud,
        StartupHudDescription,
        HudModules,
        HudModulesDescription,
        HomeDesign,
        HomeDesignDescription,
        TimeFormat,
        TimeFormatDescription,
        TimeFormatSystem,
        TimeFormatTwelveHour,
        TimeFormatTwentyFourHour,
        WorldClocks,
        WorldClocksDescription,
        ClockLabel,
        TimeZone,
        WidgetLayoutCustomization,
        WidgetLayoutCustomizationDescription,
        EditWidgetLayoutButton,
        WidgetCustomizerTitle,
        WidgetCustomizerHeader,
        WidgetCustomizerHeaderDescription,
        WidgetLivePreview,
        ActiveWidgetsHeader,
        AddWidgetsHeader,
        AddWidgetButton,
        Cancel,
        SaveAndApply,
        WidgetDigitalClock,
        WidgetMediaControls,
        WidgetMediaCompact,
        WidgetMediaArtworkSmall,
        WidgetMediaArtworkMedium,
        WidgetMediaArtworkLarge,
        WidgetMediaBlurLyrics
    }

    public static class LocalizationService
    {
        private static readonly IReadOnlyDictionary<AppLanguage, IReadOnlyDictionary<LocalizationKey, string>> Translations =
            new Dictionary<AppLanguage, IReadOnlyDictionary<LocalizationKey, string>>
            {
                [AppLanguage.Japanese] = new Dictionary<LocalizationKey, string>
                {
                    [LocalizationKey.WindowTitle] = "NoraBar 設定",
                    [LocalizationKey.AppSubtitle] = "デスクトップHUD",
                    [LocalizationKey.HudSettings] = "HUD設定",
                    [LocalizationKey.About] = "バージョン情報",
                    [LocalizationKey.DesignStyle] = "デザインスタイル",
                    [LocalizationKey.DesignStyleDescription] = "HUDのレイアウトデザイン（Minimal または Productivity）を切り替えます。",
                    [LocalizationKey.ProgressBar] = "プログレスバー表示",
                    [LocalizationKey.ProgressBarDescription] = "再生中にHUDの下部に進行状況バーを表示します。",
                    [LocalizationKey.ShowLyrics] = "同期歌詞表示",
                    [LocalizationKey.ShowLyricsDescription] = "LRCLIBから歌詞を取得し、再生時間に合わせて同期表示します。",
                    [LocalizationKey.Startup] = "システム起動時に実行",
                    [LocalizationKey.StartupDescription] = "Windowsの起動時にNoraBarを自動的に開始します。",
                    [LocalizationKey.Language] = "表示言語",
                    [LocalizationKey.LanguageDescription] = "アプリ内の表示言語を切り替えます。",
                    [LocalizationKey.Japanese] = "日本語",
                    [LocalizationKey.English] = "English",
                    [LocalizationKey.Version] = "バージョン ",
                    [LocalizationKey.CheckUpdates] = "アップデートの確認",
                    [LocalizationKey.CheckUpdatesDescription] = "GitHub Releasesから最新バージョンがあるかチェックします。",
                    [LocalizationKey.CheckUpdatesButton] = "アップデートを確認",
                    [LocalizationKey.GitHubRepository] = "GitHub リポジトリ",
                    [LocalizationKey.GitHubRepositoryDescription] = "ソースコードを公開しているリポジトリページを開きます。",
                    [LocalizationKey.OpenRepository] = "リポジトリを開く",
                    [LocalizationKey.OpenSourceLicenses] = "ライセンス情報",
                    [LocalizationKey.OpenSourceLicensesDescription] = "NoraBar本体およびサードパーティ製ライブラリのライセンスを表示します。",
                    [LocalizationKey.ShowLicenses] = "ライセンスを表示",
                    [LocalizationKey.LivePreview] = "リアルタイムプレビュー",
                    [LocalizationKey.Close] = "閉じる",
                    [LocalizationKey.ThirdPartyLicenses] = "ライセンス情報",
                    [LocalizationKey.Update] = "アップデート",
                    [LocalizationKey.Download] = "ダウンロード",
                    [LocalizationKey.SettingsMenu] = "設定...",
                    [LocalizationKey.Exit] = "終了",
                    [LocalizationKey.CheckingUpdates] = "アップデートを確認中...",
                    [LocalizationKey.UpdateAvailable] = "新しいバージョンが見つかりました: {0}",
                    [LocalizationKey.UpToDate] = "お使いのバージョンは最新です。",
                    [LocalizationKey.UpdateFailed] = "アップデートの確認に失敗しました。\nエラー: {0}",
                    [LocalizationKey.LicenseIntroTitle] = "【使用しているサードパーティ ソフトウェア】",
                    [LocalizationKey.LicensePackageVersion] = "■ CSCore (バージョン 1.2.1.2)\n■ Material.Icons.WPF (バージョン 3.0.2)",
                    [LocalizationKey.LicenseLabel] = "   ライセンス: Microsoft Public License (MS-PL) / MIT License",
                    [LocalizationKey.LicenseDetails] = "   (詳細なライセンス条文は以下を参照してください)",
                    [LocalizationKey.ThirdPartyTab] = "サードパーティ",
                    [LocalizationKey.LoadingLyrics] = "歌詞を読み込んでいます...",
                    [LocalizationKey.LyricsNotFound] = "歌詞が見つかりませんでした",
                    [LocalizationKey.LyricsNetworkError] = "ネットワークエラーが発生しました",
                    [LocalizationKey.WindowPosition] = "表示位置",
                    [LocalizationKey.WindowPositionDescription] = "HUDの表示位置をカスタマイズします。",
                    [LocalizationKey.ChangePosition] = "表示位置を変更する",
                    [LocalizationKey.ResetPosition] = "デフォルトに戻す",
                    [LocalizationKey.FinishPositionEdit] = "位置を確定する",
                    [LocalizationKey.ResetSettings] = "設定の初期化",
                    [LocalizationKey.ResetSettingsDescription] = "すべての設定をデフォルト状態に戻します。",
                    [LocalizationKey.ResetAllSettings] = "すべてリセット",
                    [LocalizationKey.ResetConfirmTitle] = "設定のリセット",
                    [LocalizationKey.ResetConfirmMessage] = "言語、デザイン、表示位置など、すべての設定を初期化しますか？\n（この操作は元に戻せません）",
                    [LocalizationKey.ResetConfirmYes] = "はい",
                    [LocalizationKey.ResetConfirmNo] = "いいえ",
                    [LocalizationKey.TextScrollMode] = "テキストの自動スクロール",
                    [LocalizationKey.TextScrollModeDescription] = "曲名などが長い場合に、自動でスクロールさせる条件を設定します。",
                    [LocalizationKey.TextScrollDisabled] = "無効（省略して表示）",
                    [LocalizationKey.TextScrollAlways] = "常に",
                    [LocalizationKey.TextScrollHoverOnly] = "ホバー時のみ",
                    [LocalizationKey.CheckUpdateOnStartup] = "起動時にアップデートを確認",
                    [LocalizationKey.CheckUpdateOnStartupDescription] = "アプリ起動時に新しいバージョンがあるか自動で確認します。",
                    [LocalizationKey.UpdateAvailableButton] = "今すぐ更新",
                    [LocalizationKey.RestartVisualizer] = "オーディオビジュアライザーの再起動",
                    [LocalizationKey.RestartVisualizerDescription] = "ビジュアライザーが動かなくなった場合に、オーディオ入力を再初期化します。",
                    [LocalizationKey.RestartVisualizerButton] = "再起動",
                    [LocalizationKey.DisableExpandOnFullscreen] = "フルスクリーン時に展開を無効化",
                    [LocalizationKey.DisableExpandOnFullscreenDescription] = "HUDがある画面でフルスクリーンのソフトウェアが起動している間、HUDの展開を無効化します。",
                    [LocalizationKey.GeneralSettings] = "一般",
                    [LocalizationKey.HudSelection] = "HUDの選択",
                    [LocalizationKey.HudSelectionDescription] = "設定するHUDを選択します。",
                    [LocalizationKey.SharedDisplaySettings] = "共通表示設定",
                    [LocalizationKey.SelectedHudSettings] = "選択中のHUD設定",
                    [LocalizationKey.MusicHudName] = "音楽HUD",
                    [LocalizationKey.HomeHudName] = "ホームHUD",
                    [LocalizationKey.NavigationStyle] = "HUDナビゲーション",
                    [LocalizationKey.NavigationStyleDescription] = "HUD切替を右側アイコンまたは上側タブで表示します。",
                    [LocalizationKey.NavigationRightRail] = "右側アイコン",
                    [LocalizationKey.NavigationTopTabs] = "上側タブ",
                    [LocalizationKey.StartupHud] = "起動時HUD",
                    [LocalizationKey.StartupHudDescription] = "アプリ起動時に最初に表示するHUDを選択します。",
                    [LocalizationKey.HudModules] = "HUDモジュール",
                    [LocalizationKey.HudModulesDescription] = "有効化と表示順を変更します。最低1つは有効にする必要があります。",
                    [LocalizationKey.HomeDesign] = "ホームデザイン",
                    [LocalizationKey.HomeDesignDescription] = "ホームHUDのレイアウトを切り替えます。",
                    [LocalizationKey.TimeFormat] = "時刻形式",
                    [LocalizationKey.TimeFormatDescription] = "ローカル時刻と世界時計の表示形式を選択します。",
                    [LocalizationKey.TimeFormatSystem] = "Windows設定に従う",
                    [LocalizationKey.TimeFormatTwelveHour] = "12時間制",
                    [LocalizationKey.TimeFormatTwentyFourHour] = "24時間制",
                    [LocalizationKey.WorldClocks] = "世界時計",
                    [LocalizationKey.WorldClocksDescription] = "2つの表示名とWindowsタイムゾーンを設定します。",
                    [LocalizationKey.ClockLabel] = "表示名",
                    [LocalizationKey.TimeZone] = "タイムゾーン",
                    [LocalizationKey.WidgetLayoutCustomization] = "ウィジェットレイアウトのカスタマイズ",
                    [LocalizationKey.WidgetLayoutCustomizationDescription] = "ドラッグ＆ドロップでHome HUDのウィジェットの編集、並び替え、追加、削除を行います。",
                    [LocalizationKey.EditWidgetLayoutButton] = "レイアウトを編集...",
                    [LocalizationKey.WidgetCustomizerTitle] = "Home HUD ウィジェットのカスタマイズ",
                    [LocalizationKey.WidgetCustomizerHeader] = "ウィジェットレイアウトのカスタマイズ",
                    [LocalizationKey.WidgetCustomizerHeaderDescription] = "ドラッグ＆ドロップでウィジェットの並び替えを行い、Home HUDをリアルタイムでプレビューできます",
                    [LocalizationKey.WidgetLivePreview] = "HUD ライブプレビュー",
                    [LocalizationKey.ActiveWidgetsHeader] = "有効なウィジェット（ドラッグして並び替え）",
                    [LocalizationKey.AddWidgetsHeader] = "ウィジェットを追加",
                    [LocalizationKey.AddWidgetButton] = "+ 追加",
                    [LocalizationKey.Cancel] = "キャンセル",
                    [LocalizationKey.SaveAndApply] = "保存して適用",
                    [LocalizationKey.WidgetDigitalClock] = "デジタル時計",
                    [LocalizationKey.WidgetMediaControls] = "メディアコントロール",
                    [LocalizationKey.WidgetMediaCompact] = "メディアコントロール (コンパクト)",
                    [LocalizationKey.WidgetMediaArtworkSmall] = "メディアコントロール (アートワーク小)",
                    [LocalizationKey.WidgetMediaArtworkMedium] = "メディアコントロール (アートワーク中)",
                    [LocalizationKey.WidgetMediaArtworkLarge] = "メディアコントロール (アートワーク大)",
                    [LocalizationKey.WidgetMediaBlurLyrics] = "メディアコントロール (背景ぼかし＆歌詞)"
                },
                [AppLanguage.English] = new Dictionary<LocalizationKey, string>
                {
                    [LocalizationKey.WindowTitle] = "NoraBar Settings",
                    [LocalizationKey.AppSubtitle] = "Desktop HUD",
                    [LocalizationKey.HudSettings] = "HUD Settings",
                    [LocalizationKey.About] = "About",
                    [LocalizationKey.DesignStyle] = "Design Style",
                    [LocalizationKey.DesignStyleDescription] = "Switches the HUD layout between Minimal and Productivity.",
                    [LocalizationKey.ProgressBar] = "Progress Bar",
                    [LocalizationKey.ProgressBarDescription] = "Shows the playback progress bar at the bottom of the HUD.",
                    [LocalizationKey.ShowLyrics] = "Synced Lyrics",
                    [LocalizationKey.ShowLyricsDescription] = "Fetches and displays synced lyrics of the playing track using LRCLIB.",
                    [LocalizationKey.Startup] = "Run at System Startup",
                    [LocalizationKey.StartupDescription] = "Starts NoraBar automatically when Windows starts.",
                    [LocalizationKey.Language] = "Display Language",
                    [LocalizationKey.LanguageDescription] = "Changes the language used in the app.",
                    [LocalizationKey.Japanese] = "日本語",
                    [LocalizationKey.English] = "English",
                    [LocalizationKey.Version] = "Version ",
                    [LocalizationKey.CheckUpdates] = "Check for Updates",
                    [LocalizationKey.CheckUpdatesDescription] = "Checks GitHub Releases for the latest version.",
                    [LocalizationKey.CheckUpdatesButton] = "Check Updates",
                    [LocalizationKey.GitHubRepository] = "GitHub Repository",
                    [LocalizationKey.GitHubRepositoryDescription] = "Opens the repository page where the source code is published.",
                    [LocalizationKey.OpenRepository] = "Open Repository",
                    [LocalizationKey.OpenSourceLicenses] = "License Information",
                    [LocalizationKey.OpenSourceLicensesDescription] = "Shows licenses for NoraBar and the third-party libraries used.",
                    [LocalizationKey.ShowLicenses] = "Show Licenses",
                    [LocalizationKey.LivePreview] = "Live Preview",
                    [LocalizationKey.Close] = "Close",
                    [LocalizationKey.ThirdPartyLicenses] = "License Information",
                    [LocalizationKey.Update] = "Update",
                    [LocalizationKey.Download] = "Download",
                    [LocalizationKey.SettingsMenu] = "Settings...",
                    [LocalizationKey.Exit] = "Exit",
                    [LocalizationKey.CheckingUpdates] = "Checking for updates...",
                    [LocalizationKey.UpdateAvailable] = "A new version is available: {0}",
                    [LocalizationKey.UpToDate] = "You are using the latest version.",
                    [LocalizationKey.UpdateFailed] = "Failed to check for updates.\nError: {0}",
                    [LocalizationKey.LicenseIntroTitle] = "Third-party software used by NoraBar",
                    [LocalizationKey.LicensePackageVersion] = "CSCore (version 1.2.1.2)\nMaterial.Icons.WPF (version 3.0.2)",
                    [LocalizationKey.LicenseLabel] = "   License: Microsoft Public License (MS-PL) / MIT License",
                    [LocalizationKey.LicenseDetails] = "   See the license text below for details.",
                    [LocalizationKey.ThirdPartyTab] = "Third-party",
                    [LocalizationKey.LoadingLyrics] = "Loading lyrics...",
                    [LocalizationKey.LyricsNotFound] = "Lyrics not found",
                    [LocalizationKey.LyricsNetworkError] = "Network error occurred",
                    [LocalizationKey.WindowPosition] = "Window Position",
                    [LocalizationKey.WindowPositionDescription] = "Customize the HUD display position.",
                    [LocalizationKey.ChangePosition] = "Change Position",
                    [LocalizationKey.ResetPosition] = "Reset to Default",
                    [LocalizationKey.FinishPositionEdit] = "Finish Edit",
                    [LocalizationKey.ResetSettings] = "Reset Settings",
                    [LocalizationKey.ResetSettingsDescription] = "Resets all settings to their default values.",
                    [LocalizationKey.ResetAllSettings] = "Reset All",
                    [LocalizationKey.ResetConfirmTitle] = "Reset Settings",
                    [LocalizationKey.ResetConfirmMessage] = "Are you sure you want to initialize all settings including language, design, and window position?\n(This cannot be undone)",
                    [LocalizationKey.ResetConfirmYes] = "Yes",
                    [LocalizationKey.ResetConfirmNo] = "No",
                    [LocalizationKey.TextScrollMode] = "Auto Scroll Text",
                    [LocalizationKey.TextScrollModeDescription] = "Condition for automatically scrolling long titles and artist names.",
                    [LocalizationKey.TextScrollDisabled] = "Disabled (Truncate)",
                    [LocalizationKey.TextScrollAlways] = "Always",
                    [LocalizationKey.TextScrollHoverOnly] = "Hover Only",
                    [LocalizationKey.CheckUpdateOnStartup] = "Check for Updates on Startup",
                    [LocalizationKey.CheckUpdateOnStartupDescription] = "Automatically check for new versions when the app starts.",
                    [LocalizationKey.UpdateAvailableButton] = "Update Now",
                    [LocalizationKey.RestartVisualizer] = "Restart Audio Visualizer",
                    [LocalizationKey.RestartVisualizerDescription] = "Reinitializes audio capture if the visualizer stops working.",
                    [LocalizationKey.RestartVisualizerButton] = "Restart",
                    [LocalizationKey.DisableExpandOnFullscreen] = "Disable Expansion in Fullscreen",
                    [LocalizationKey.DisableExpandOnFullscreenDescription] = "Disables HUD expansion while a fullscreen application is running on the HUD's screen.",
                    [LocalizationKey.GeneralSettings] = "General",
                    [LocalizationKey.HudSelection] = "HUD Selection",
                    [LocalizationKey.HudSelectionDescription] = "Select the desktop HUD to configure.",
                    [LocalizationKey.SharedDisplaySettings] = "Shared Display Settings",
                    [LocalizationKey.SelectedHudSettings] = "Selected HUD Settings",
                    [LocalizationKey.MusicHudName] = "Music HUD",
                    [LocalizationKey.HomeHudName] = "Home HUD",
                    [LocalizationKey.NavigationStyle] = "HUD Navigation",
                    [LocalizationKey.NavigationStyleDescription] = "Shows HUD navigation as right-side icons or top tabs.",
                    [LocalizationKey.NavigationRightRail] = "Right-side icons",
                    [LocalizationKey.NavigationTopTabs] = "Top tabs",
                    [LocalizationKey.StartupHud] = "Startup HUD",
                    [LocalizationKey.StartupHudDescription] = "Selects the HUD shown first when the app starts.",
                    [LocalizationKey.HudModules] = "HUD Modules",
                    [LocalizationKey.HudModulesDescription] = "Enable and reorder HUDs. At least one HUD must remain enabled.",
                    [LocalizationKey.HomeDesign] = "Home Design",
                    [LocalizationKey.HomeDesignDescription] = "Changes the Home HUD layout.",
                    [LocalizationKey.TimeFormat] = "Time Format",
                    [LocalizationKey.TimeFormatDescription] = "Selects the format used by local and world clocks.",
                    [LocalizationKey.TimeFormatSystem] = "Use Windows settings",
                    [LocalizationKey.TimeFormatTwelveHour] = "12-hour",
                    [LocalizationKey.TimeFormatTwentyFourHour] = "24-hour",
                    [LocalizationKey.WorldClocks] = "World Clocks",
                    [LocalizationKey.WorldClocksDescription] = "Configure two labels and Windows time zones.",
                    [LocalizationKey.ClockLabel] = "Label",
                    [LocalizationKey.TimeZone] = "Time zone",
                    [LocalizationKey.WidgetLayoutCustomization] = "Widget Layout Customization",
                    [LocalizationKey.WidgetLayoutCustomizationDescription] = "Edit, reorder, add, or remove widgets on your Home HUD with drag and drop.",
                    [LocalizationKey.EditWidgetLayoutButton] = "Edit Layout...",
                    [LocalizationKey.WidgetCustomizerTitle] = "Home HUD Widget Customizer",
                    [LocalizationKey.WidgetCustomizerHeader] = "Widget Layout Customizer",
                    [LocalizationKey.WidgetCustomizerHeaderDescription] = "Drag and drop widgets to reorder and preview your Home HUD in real-time",
                    [LocalizationKey.WidgetLivePreview] = "HUD Live Preview",
                    [LocalizationKey.ActiveWidgetsHeader] = "Active Widgets (Drag to Reorder)",
                    [LocalizationKey.AddWidgetsHeader] = "Add Widgets",
                    [LocalizationKey.AddWidgetButton] = "+ Add",
                    [LocalizationKey.Cancel] = "Cancel",
                    [LocalizationKey.SaveAndApply] = "Save & Apply",
                    [LocalizationKey.WidgetDigitalClock] = "Digital Clock",
                    [LocalizationKey.WidgetMediaControls] = "Media Controls",
                    [LocalizationKey.WidgetMediaCompact] = "Media Controls (Compact)",
                    [LocalizationKey.WidgetMediaArtworkSmall] = "Media Controls (Small Artwork)",
                    [LocalizationKey.WidgetMediaArtworkMedium] = "Media Controls (Medium Artwork)",
                    [LocalizationKey.WidgetMediaArtworkLarge] = "Media Controls (Large Artwork)",
                    [LocalizationKey.WidgetMediaBlurLyrics] = "Media Controls (Blur & Lyrics)"
                }
            };

        public static string GetText(AppLanguage language, LocalizationKey key)
        {
            if (Translations.TryGetValue(language, out var languageTranslations) &&
                languageTranslations.TryGetValue(key, out var text))
            {
                return text;
            }

            return Translations[AppLanguage.Japanese][key];
        }
    }
}
